parameters:
#    tv_guide_listings.example.class: TVGuide\ListingsBundle\Example

services:
#    tv_guide_listings.example:
#        class: %tv_guide_listings.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
